version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1
  kubernetes: circleci/kubernetes@1.0.2
  aws-eks: circleci/aws-eks@1.1

commands:
jobs:
  build-docker:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64
            sudo chmod +x /bin/hadolint
      - run:
          name: run lint
          command: |
            . venv/bin/activate 
            make lint
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t uchitavietnam/udacity-devops-capstone:latest .
      - run:
          name: Log in to Docker Hub
          command: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run:
          name: Push Docker image
          command: docker push uchitavietnam/udacity-devops-capstone:latest

  deploy-to-eks:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install awscli and gettext-base
          command: |
            sudo pip3 install awscli
            sudo apt-get install gettext-base
      - run:
          name: Install AWS CLI
          command: |
            curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
      # - run:
      #     name: Install aws-iam-authenticator
      #     command: |
      #       curl -o aws-iam-authenticator curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/aws-iam-authenticator
      #       chmod +x ./aws-iam-authenticator
      #       sudo mv ./aws-iam-authenticator /usr/local/bin/aws-iam-authenticator
      - run:
          name: Install kubectl
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.13.7/2019-06-11/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
      - run:
          name: Connect to cluster
          command: |
            aws eks --region us-east-1 update-kubeconfig --name devops-capstone
      - run:
          name: Prepare K8S template
          command: |
            rm -rf .k8s/.generated && mkdir -p .circleci/.k8s/.generated
            for f in .circleci/.k8s/deployment.yaml
              do
              envsubst < $f > ".circleci/.k8s/.generated/$(basename $f)"
            done
      - run:
          name: Debugging
          command: |
            kubectl config view
            kubectl config current-context
            aws iam list-attached-user-policies --user-name udacity-devops-capstone
      - run:
          name: Deploy
          command: |
            kubectl apply -f .circleci/.k8s/.generated/
            kubectl get pod

workflows:
  default:
    jobs:
      - build-docker
      - deploy-to-eks:
          requires: [build-docker]
