apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-capstone
  template:
    metadata:
      labels:
        app: devops-capstone
    spec:
      containers:
      - name: devops-capstone
        image: uchitavietnam/udacity-devops-capstone:latest
        imagePullPolicy: Always
        ports:
        - protocol: TCP
          containerPort: 80
          targetPort: 80
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%